---
execute:
  enabled: true
---

# Numpy and Pandas {#sec-numpy-and-pandas}

If you know a bit of linear algebra, you know how some computations are more easily expressed as vectors or matrices. The [NumPy library](https://numpy.org/devdocs/user/index.html#user) provides a  multidimensional array object that lets you do that. You already installed `numpy` when the beginning of the course, so all you have to do is import it. The cell below imports the `numpy` module and binds it to the name `np`. This is the way every one imports it and saves you a view keystrokes every time you need to use it.

In [1]:
import numpy as np

## Arrays

In [2]:
numbers = [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
np.array(numbers)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

All the linear algebra rules apply to arrays:

::: {.content-margin}

You may see this behavior referred to as *broadcasting*, but that is just the programming term for linear algebra way of doing computations.

:::

In [3]:
a = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a + b)
print(a * b)
print(a + 10)

[9 9 9 9 9 9 9 9 9 9]
[ 0  8 14 18 20 20 18 14  8  0]
[19 18 17 16 15 14 13 12 11 10]

Arrays also come with a lot of useful methods like:

In [4]:
a.mean()

np.float64(4.5)

::: {.content-margin}

`np.float64` is Numpy's own float type, which works the same as the regular `float`.

:::

You can make a arrays with any number of dimensions. A two-dimensional array corresponds to a matrix. You already know how to represent a matrix as a list of lists. To make a matrix, just turn that into an array:

In [5]:
list_of_lists = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]

matrix = np.array(list_of_lists)
matrix

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

You can access elements with square brackets just like you do with lists:

In [6]:
list_of_lists[1][1]

2

In [7]:
matrix[1]

array([1, 2, 3])

In [8]:
matrix[1][1]

np.int64(2)

For computational efficiency, numpy arrays also lets you specify indices for each dimension in a single set of square brackets:

In [9]:
matrix[1]

array([1, 2, 3])

In [10]:
matrix[1, 1]

np.int64(2)

Many of the array methods can be used both on the entire array, but also separately for the rows or columns:

In [11]:
matrix.sum()

np.int64(18)

Pass `axis=0` to get the row sums:

In [12]:
matrix.mean(axis=0)

array([1., 2., 3.])

Pass `axis=1` to get the column sums:

In [13]:
matrix.mean(axis=1)

array([2., 2., 2.])

## The Pandas library

Run this cell to download an example data set to a `penguins.csv` file next to this notebook. Then open it to see what the contents look like and close it again (do not change it).

In [14]:
import seaborn as sns
sns.load_dataset('penguins').to_csv('penguins.csv', index=False)

As you can see, `penguins.csv` is a table with a header line and lots of rows. The values in each row are separated by a comma, which is why the file name ends with `.csv`. CSV is short for *comma-separated values*. This kind of table format is one of the most common ways of storing data. Pandas is a rich and powerful library that lets you do all kinds of manipulation and advanced data analysis on such table data. This chapter shows introduces you to the basics, but if/when you need to, you can find all the information you need in the [Pandas user guide](https://pandas.pydata.org/docs/user_guide/index.html#user-guide).

You already installed `pandas` when the beginning of the course, so all you have to do is import it. The cell below imports the `pandas` module and binds it to the name `pd`. This is the way every one imports it and saves you a view keystrokes every time you need to use it.

In [15]:
import pandas as pd

If you are not convinced, you can use `type` to check which kind it is:

In [16]:
type(pd)

module

## DataFrames {#sec-dataframes}

You can read in the table data in `penguins.csv` using the `read_csv` function in the `pandas` module (available as the `pd` name). Lets do that and store it in a variable called `penguins`:

In [17]:
penguins = pd.read_csv('penguins.csv')

Pandas `read_csv` creates `DataFrame` object. `DataFrame` is the main object of Pandas and its way of representing table data.

In [18]:
type(penguins)

pandas.DataFrame

If you put a dataframe on the last (or only) line in a cell, it display it nicely. If it has many rows, it will only show the first and last five rows.

In [19]:
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

I see just the first or last rows, you can use the `head` and `tail` methods:

In [20]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [21]:
penguins.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

#### Exercise

[SOLO](../intro/course-introduction.qmd#sec-badge-solo){.small}

Look at the `DataFrame` [documentation page](https://pandas.pydata.org/docs/reference/frame.html) and find the method you need to sort the rows of a dataframe. Then sort the penguins data by "flipper_length_mm".

## Extracting data

To access a column, you can use the familiar square brackets that we also use with strings, lists and dictionaries:

In [23]:
bill_depth = penguins['bill_depth_mm']
bill_depth

0      18.7
1      17.4
2      18.0
3       NaN
4      19.3
       ...
339     NaN
340    14.3
341    15.7
342    14.8
343    16.1
Name: bill_depth_mm, Length: 344, dtype: float64

::: {.content-margin}

You may see other people access the columns as attributes (like `penguins.bill_depth_mm`), but we will stick to the bracket notation to keep it simple.

:::

Columns is has their own type, `Series`.

In [24]:
type(bill_depth)

pandas.Series

Its data is just a numpy array, but on top of that it packs a lot of useful methods for computing statistics like the `mean` or for manipulating like `sort_values`:

In [25]:
bill_depth.mean()

np.float64(17.151169590643278)

::: {.content-margin}

`np.float64` is Numpy's own float type, which works the same as the regular `float`.

:::

You can see all the other methods on the `Series` [documentation page](https://pandas.pydata.org/docs/reference/api/pandas.Series.html).

## Indexing

You may have noticed the numbers in the far left column that does not have a name. That is the row index that you need to access individual rows. Dataframes have a `loc` attribute that you can use for accessing data in all kinds of ways. To get a row, you just give it the row index in square brackets:

In [26]:
row = penguins.loc[4]
type(row)

pandas.Series

The row is returned as a `Series` indexed by the column names:

In [27]:
row

species                 Adelie
island               Torgersen
bill_length_mm            36.7
bill_depth_mm             19.3
flipper_length_mm        193.0
body_mass_g             3450.0
sex                     Female
Name: 4, dtype: object

So you can access the values by passing column names to `loc`:

In [28]:
row.loc['island']

'Torgersen'

You an get the same single dataframe cell by passing both a row and a column index value to `loc`:

In [29]:
penguins.loc[4, 'island']

'Torgersen'

You can also access data using slices or lists of row and column values index values:

In [30]:
penguins.loc[40:45, ['island', 'body_mass_g']]

   island  body_mass_g
40  Dream       3150.0
41  Dream       3900.0
42  Dream       3100.0
43  Dream       4400.0
44  Dream       3000.0
45  Dream       4600.0

In [31]:
penguins.loc[[7,153,257], ['sex', 'species']]

      sex    species
7    Male     Adelie
153  Male  Chinstrap
257  Male     Gentoo

Rather than providing row index values, you can provide a series with a `True` or `False` for each row. Since `Series` support *boadcasting* the same way arrays do, statements like this produce such True/False series:

In [32]:
is_adelie = penguins['species'] == 'Adelie'
is_adelie

0       True
1       True
2       True
3       True
4       True
       ...
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

Passing that to `penguins.loc` gives you all the rows where the "species" column as the value `"Adelie"`:

In [33]:
penguins.loc[is_adelie]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,Female
148,Adelie,Dream,36.0,17.8,195.0,3450.0,Female
149,Adelie,Dream,37.8,18.1,193.0,3750.0,Male
150,Adelie,Dream,36.0,17.1,187.0,3700.0,Female
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male

#### Exercise

[SOLO](../intro/course-introduction.qmd#sec-badge-solo){.small}

Extract the rows where values in the "body_mass_g" column is larger than 4500.

#### Exercise

[SOLO](../intro/course-introduction.qmd#sec-badge-solo){.small}

Extract the rows where values in the "body_mass_g" column is larger than 4500 *and* the the values in the "species" columns is `"Adelie"`. Hint: You can use the loc twice to achieve this.

#### Exercise
 
[AI: Explainer](../intro/course-introduction.qmd#sec-badge-explainer){.small}

Now that you know the basics of extracting data, try to ask the AI to give you a brief account of how the `DataFrame.loc` works. Then cross-check its explanation with the online documentation.

## Build `DataFrame` from data

Sometimes the table data is not something your read in from a file, but data you are building inside your notebook. In that case, you can easily turn your data into a `DataFrame`. You create a `DataFrame` by either specifying its columns or its rows. To create it from columns you first make a dictionary where keys are column names and the values are lists with column values and then pass that dictionary as data to `DataFrame()`:

In [35]:
columns_dict = {'seq_id': ['A', 'B', 'C'], 'gc_content': [0.452, 0.421, 0.421]}
gc_data = pd.DataFrame(columns_dict)
gc_data

  seq_id  gc_content
0      A       0.452
1      B       0.421
2      C       0.421

You can also make a `DataFrame` from rows, you first make a list of lists and then pass that as argument to the the `from_records` method of `DataFrame`:

In [36]:
row_records = [('A', 0.452), ('B', 0.421), ('C', 0.421)]
gc_data = pd.DataFrame().from_records(row_records, columns=['seq_id', 'gc_content'])
gc_data

  seq_id  gc_content
0      A       0.452
1      B       0.421
2      C       0.421

If you want to save your `gc_data` as a CSV file, you can save it to a file like this:

In [37]:
gc_data.to_csv('gc_data.csv')

## Grouping

In [38]:
penguins.groupby('island').mean(numeric_only=True)

           bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
island
Biscoe          45.257485      15.874850         209.706587  4716.017964
Dream           44.167742      18.344355         193.072581  3712.903226
Torgersen       38.950980      18.429412         191.196078  3706.372549

#### Exercise

[SOLO](../intro/course-introduction.qmd#sec-badge-solo){.small}

Extract the rows where values in the "body_mass_g" column is larger than 4500.

## Much more to learn as you need it

This is a small chapter about a very large module, and a lot of powerful techniques have been left out. You can do pretty much anything you might want to do with tables. To get a taste, you can browse [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html).